version: 2
registries:
  particular-packages:
    type: nuget-feed
    url: https://f.feedz.io/particular-software/packages/nuget/index.json
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
