name: 'Particular Software Version Monkey'
description: 'Updates dependency versions'
runs:
  using: "composite"
  steps:
    - name: Run VersionMonkey
      shell: pwsh
      run: |
        dotnet run --project ${{ github.action_path }}/src/VersionMonkey/VersionMonkey.csproj --configuration Release