name: 'Particular Software Dependency Updates'
description: 'Updates dependency versions'
runs:
  using: "composite"
  steps:
    - name: Run DependencyUpdates
      shell: pwsh
      run: |
        dotnet run --project ${{ github.action_path }}/src/DependencyUpdates/DependencyUpdates.csproj --configuration Release