name: DependencyUpdates
on:
  workflow_call:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: bash
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          # Needs to match the .NET version of the DependencyUpdates C# code
          dotnet-version: 9.0.x
      - name: Run action
        uses: Particular/dependency-updates-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}