name: DependencyUpdates
on:
  workflow_call:
    inputs:
      command:
        type: string
        description: The update for the dependency updater application to perform
        required: true
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: bash
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          # Get all history for all branches and tags
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          # Needs to match the .NET version of the DependencyUpdates C# code
          dotnet-version: 9.0.x
      - name: Run dependency tool
        uses: Particular/dependency-updates-action@update-command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          APP_COMMAND: ${{ inputs.command }}